spring:
  datasource:
    url: jdbc:mysql://localhost:3306/SkillMaker?createDatabaseIfNotExist=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    show-sql: true

  jackson:
    mapper:
      accept-case-insensitive-enums: true

server:
  port: 8080

springdoc:
  api-docs.path: /api-docs

jwt:
  secret: tajne_heslo_skillmaker_123456789
  expiration: 3600000